server: 
  port: 5506

# Logging
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}, %X{traceId:-n/a}] | %-20.20thread | %highlight(%-5level) | %cyan(%-25.25logger{25}) | %m%n"
  level:
    com:
      shopper: DEBUG
    org:
      springframework:
        web: INFO
        security: INFO
    web: INFO
    root: INFO

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: notification-service

  # Event Streaming
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      security:
        protocol: PLAINTEXT

# Tracing & Observability
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0