name: service-workflow

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_TAG: ga-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build & Publish Docker Image to Github Packages
      run: |
        export CONTAINER_REGISTRY=${{ env.CONTAINER_REGISTRY }}
        export IMAGE_TAG=${{ env.IMAGE_TAG }}
        
        if [ ! -z "${{ inputs.main-class }}" ]; then
          MAIN_CLASS_ARGS="-Djib.container.mainClass=${{ inputs.main-class }}"
        fi
        
        mvn clean package jib:dockerBuild \
        -Djib.to.auth.username=${{ github.actor }} \
        -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} \
        -B -am -ntp -pl ${{ inputs.service }} \
        $MAIN_CLASS_ARGS
      shell: bash
