name: shopper-payment-service

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - shopper-payment-service/**
      - shopper-shared/**
      - .github/workflows/shopper-payment-service.yml
      - pom.xml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: shopper-payment-service
      main-class: PaymentServiceApplication
