name: shopper-order-service

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - shopper-order-service/**
      - shopper-shared/**
      - .github/workflows/shopper-order-service.yml
      - pom.xml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: shopper-order-service
      main-class: OrderServiceApplication
