name: shopper-api-gateway

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - shopper-api-gateway/**
      - shopper-shared/**
      - .github/workflows/shopper-api-gateway.yml
      - pom.xml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: shopper-api-gateway
      main-class: ApiGatewayApplication
